# Generated by Django 5.0.4 on 2024-05-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("links", models.CharField(max_length=400)),
                ("imgs", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
