# Generated by Django 5.0.4 on 2024-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="links",
            field=models.CharField(max_length=300),
        ),
    ]
