# Generated by Django 5.0.4 on 2024-05-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0002_project_tags_project_title_alter_project_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default="M",
                max_length=1,
            ),
        ),
    ]
