# Generated by Django 5.0.6 on 2024-06-08 16:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0003_project_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="imgs",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
