# Generated by Django 5.0.6 on 2024-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0004_alter_project_imgs"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="imgs",
            field=models.ImageField(upload_to="pics"),
        ),
    ]
