# Generated by Django 5.0.6 on 2024-06-09 15:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0005_project_image_url_alter_project_imgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="project",
            name="imgs",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
