# Generated by Django 5.0.6 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectdatabase", "0006_remove_project_image_url_alter_project_imgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="imgs",
            field=models.ImageField(upload_to="pics"),
        ),
    ]
